-- The Northwoods University Student Registration Database

-- USE statement
USE master
GO

IF EXISTS(SELECT * from sys.databases WHERE name='NorthwoodsUniversity')  
BEGIN  
    DROP DATABASE NorthwoodsUniversity;  
END  

CREATE DATABASE NorthwoodsUniversity;  

USE NorthwoodsUniversity 
GO

-- Table drops
DROP TABLE IF EXISTS Location_T;
DROP TABLE IF EXISTS Faculty_T;
DROP TABLE IF EXISTS Student_T;
DROP TABLE IF EXISTS Term_T;
DROP TABLE IF EXISTS Course_T;
DROP TABLE IF EXISTS Course_Section_T;
DROP TABLE IF EXISTS Enrollment_T;


-- Location table
CREATE TABLE Location_T
(
LOC_ID INT NOT NULL,
Building_Code INT NOT NULL,
Room INT NOT NULL,
CONSTRAINT PK_LOCID PRIMARY KEY(LOC_ID)
);

-- Faculty table
CREATE TABLE Faculty_T
(
F_ID INT NOT NULL,
F_FirstName VARCHAR(50) NOT NULL,
F_LastName VARCHAR(50) NOT NULL,
F_Phone VARCHAR(50) NOT NULL,
F_PIN INT NOT NULL,
Time_Enrolled DATETIME NOT NULL,
LOC_ID INT NOT NULL,
F_Rank VARCHAR(50) NOT NULL,
CONSTRAINT PK_FID PRIMARY KEY(F_ID),
CONSTRAINT FK_LOCID FOREIGN KEY(LOC_ID) REFERENCES Location_T(LOC_ID)
);

-- Student table
CREATE TABLE Student_T
(
S_ID INT NOT NULL,
S_FirstName VARCHAR(50) NOT NULL,
S_LastName VARCHAR(50) NOT NULL,
S_Address VARCHAR(50) NOT NULL,
S_City VARCHAR(50) NOT NULL,
S_State VARCHAR(50) NOT NULL,
S_Zip VARCHAR(50) NOT NULL,
S_Phone VARCHAR(50) NOT NULL,
S_Class VARCHAR(50) NOT NULL,
S_PIN INT NOT NULL,
Time_Enrolled DATETIME NOT NULL,
F_ID INT NOT NULL,
S_DOB INT NOT NULL,
Advisor VARCHAR(50) NOT NULL,
CONSTRAINT PK_SID PRIMARY KEY(S_ID),
CONSTRAINT FK_FID FOREIGN KEY(F_ID) REFERENCES Faculty_T(F_ID)
);

-- Term table
CREATE TABLE Term_T
(
Term_ID INT NOT NULL,
STATUS VARCHAR(50) NOT NULL,
CONSTRAINT PK_TermID PRIMARY KEY(Term_ID)
);

-- Course table
CREATE TABLE Course_T
(
Course_ID INT NOT NULL,
Course_Name VARCHAR(50) NOT NULL,
Credits INT NOT NULL,
CONSTRAINT PK_CourseID PRIMARY KEY(Course_ID)
);

-- Course_Section table
CREATE TABLE Course_Section_T
(
Course_Section_ID INT NOT NULL,
Course_ID INT NOT NULL,
Term_ID INT NOT NULL,
Section_Number INT NOT NULL,
F_ID INT NOT NULL,
MAX_Enrollment INT NOT NULL,
LOC_ID INT NOT NULL,
Duration DATETIME NOT NULL,
CONSTRAINT PK_CourseSectionID PRIMARY KEY(Course_Section_ID),
CONSTRAINT FK_CourseID FOREIGN KEY(Course_ID) REFERENCES Course_T(Course_ID),
CONSTRAINT FK_TermID FOREIGN KEY(Term_ID) REFERENCES Term_T(Term_ID),
CONSTRAINT FK_FID1 FOREIGN KEY(F_ID) REFERENCES Faculty_T(F_ID),
CONSTRAINT FK_LOCID1 FOREIGN KEY(LOC_ID) REFERENCES Location_T(LOC_ID)
);

-- Enrollment table
CREATE TABLE Enrollment_T
(
S_ID INT NOT NULL,
Course_Section_ID INT NOT NULL,
GRADE VARCHAR(50) NOT NULL,
CONSTRAINT PK_ENROLLMENT PRIMARY KEY(S_ID, Course_Section_ID),
CONSTRAINT FK_SID FOREIGN KEY(S_ID) REFERENCES Student_T(S_ID),
CONSTRAINT FK_CourseSectionID FOREIGN KEY(Course_Section_ID) REFERENCES Course_Section_T(Course_Section_ID)
);
